name: actions

on: [push, pull_request] # 触发事件

jobs:
  bt-product-release:
    if: ${{ github.ref == 'refs/heads/main' }}  # 检测main分支是否有更新
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=`cat Dockerfile|grep VERSION|awk '{print $2}'`
        docker login ccr.ccs.tencentyun.com --username=${{ secrets.TCR_USERNAME }} --password=${{ secrets.TCR_PASSWORD }}
        docker login docker.io --username=${{ secrets.DOCKERHUBUSER }} --password=${{ secrets.DOCKERHUBPASSWD }} 
        docker build -t ccr.ccs.tencentyun.com/fanpix/ollama:$IMAGE_TAG .
        docker push ccr.ccs.tencentyun.com/fanpix/ollama:$IMAGE_TAG