name: actions

on: [push, pull_request] # 触发事件

jobs:
  bt-product-release:
    if: ${{ github.ref == 'refs/heads/main' }}  # 检测main分支是否有更新
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
        region-id: cn-hangzhou # 务必正确填写镜像容器服务的登录地址
        username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=`cat Dockerfile|grep VERSION|awk '{print $2}'`
        docker login docker.io --username=${{ secrets.DOCKERHUBUSER }} --password=${{ secrets.DOCKERHUBPASSWD }} 
        docker build -t registry.cn-hangzhou.aliyuncs.com/rxopy/ollama:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/rxopy/ollama:$IMAGE_TAG